#!/usr/bin/env bash

# Turn off echo 关闭回显
set +x

# 将工作目录设置为脚本所在目录
# shellcheck disable=SC2164
cd "$(dirname "$0")"

git remote -v
git fetch
git rebase origin/main

folder="ComposeCore"
if [ -d "$PWD/$folder" ]; then
    # shellcheck disable=SC2164
    cd $folder
    echo "准备拉取仓库：$folder"
    git remote -v
    git fetch
    git rebase origin/main
    # shellcheck disable=SC2103
    cd ..
else
    echo "准备克隆仓库：$folder"
    git clone git@github.com:angcyo/ComposeCore.git
fi

folder="ComposeExtend"
if [ -d "$PWD/$folder" ]; then
    # shellcheck disable=SC2164
    cd $folder
    echo "准备拉取仓库：$folder"
    git remote -v
    git fetch
    git rebase origin/main
    # shellcheck disable=SC2103
    cd ..
else
    echo "准备克隆仓库：$folder"
    git clone git@github.com:angcyo/ComposeExtend.git
fi

# read -n 1 -s -r -p "!结束! Press any key to continue..."
